//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Management_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bankEntities1 : DbContext
    {
        public bankEntities1()
            : base("name=bankEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Balance_amt> Balance_amt { get; set; }
        public virtual DbSet<Cashdeposit> Cashdeposits { get; set; }
        public virtual DbSet<cust_newaccounts> cust_newaccounts { get; set; }
        public virtual DbSet<deposit> deposits { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<teams_info> teams_info { get; set; }
        public virtual DbSet<transferamt> transferamts { get; set; }
        public virtual DbSet<withdrawal> withdrawals { get; set; }
    }
}
