//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cashdeposit
    {
        public int deposit_id { get; set; }
        public string acc_num { get; set; }
        public string deposit_amt { get; set; }
    }
}
