//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class cust_newaccounts
    {
        public int Cust_id { get; set; }
        public string Cust_firstname { get; set; }
        public string Cust_lastname { get; set; }
        public System.DateTime Date_of_birth { get; set; }
        public string Trn_num { get; set; }
        public string Cust_phone { get; set; }
        public string Cust_address { get; set; }
        public string Occupation { get; set; }
        public string Deposit_StartAMT { get; set; }
        public System.DateTime Date_of_deposit { get; set; }
        public string Cust_Gender { get; set; }
    }
}
