//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class teams_info
    {
        public int agent_id { get; set; }
        public string emp_firstname { get; set; }
        public string emp_lastname { get; set; }
        public string emp_address { get; set; }
        public string emp_phone { get; set; }
        public string emp_username { get; set; }
        public string user_password { get; set; }
        public string job { get; set; }
    }
}
