//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Banking_Management_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class transferamt
    {
        public int transfer_id { get; set; }
        public string from_accnum { get; set; }
        public string to_accnum { get; set; }
        public string amount_trans { get; set; }
    }
}
